### ISSUE TITLE
Iosevka formula: supported features

### ISSUE THREAD

**Issue by robertgzr** [robertgzr/homebrew-tap#5]
https://github.com/be5invis/Iosevka#build-your-own-style

- [x] fonts
  - [x] TTF
  - [x] TTF (unhinted)
  - [x] WOFF
  - [x] WOFF2
- [x] weights (can exclude)
  - [x] thin
  - [x] extralight
  - [x] light
  - [x] regular
  - [x] medium
  - [x] semibold
  - [x] bold
  - [x] extrabold
  - [x] heavy
- [x] slants (can exclude)
  - [x] upright
  - [x] italic
  - [x] oblique
- [x] general shape:
  - [x] `sans`
  - [x] `slab`
- [x] spacing and ligation styles:
  - [x] `term`
  - [x] `termlig`
  - [x] `type`
  - [x] `stress-fw`
- [x] stylistic sets: `ss01`~`ss11`
- [x] ligation styles
  - [x] `haskell`
  - [x] `idris`
  - [x] `coq`
  - [x] `elm`
  - [x] `ml`
  - [x] `fs`
  - [x] `fstar`
  - [x] `swift`
  - [x] `purescript`
- [ ] line spacing: `leading-750`\~`leading-2000`
- [ ] powerline symbol positioning
  - [ ] `powerline-scale-y-750`\~`powerline-scale-y-1500` 
  - [ ] `powerline-scale-x-750`\~`powerline-scale-x-1500` 
  - [ ] `powerline-shift-y-n500`\~`powerline-shift-y-n50`, 
`powerline-shift-y-0`,  
`powerline-shift-y-p50`\~`powerline-shift-y-p500`
  - [ ] `powerline-shift-x-n500`\~`powerline-shift-x-n50`, 
`powerline-shift-x-0`,  
`powerline-shift-x-p50`\~`powerline-shift-x-p500`
- [x] width modifiers
  - [x] `expanded`
  - [x] `compressed`
- [x] character variants; correspond with the `cv##` styles
  - [x] letter `l`
    - [x] `v-l-hooky`
    - [x] `v-l-zshaped`
    - [x] `v-l-serifed`
    - [x] `v-l-italic`
    - [x] `v-l-tailed`
    - [x] `v-l-hookybottom`
    - [x] `v-l-line`
  - [x] letter `i`
    - [x] `v-i-hooky`
    - [x] `v-i-zshaped`
    - [x] `v-i-serifed`
    - [x] `v-i-italic`
    - [x] `v-i-line`
  - [x] letter `j`
    - [x] `v-j-serifed`
    - [x] `v-j-line`
  - [x] letter `a`
    - [x] `v-a-singlestorey`
    - [x] `v-l-doublestorey`
  - [x] letter `f`
    - [x] `v-f-straight`
    - [x] `v-f-tailed`
  - [x] letter `g`
    - [x] `v-g-doublestorey`
    - [x] `v-g-singlestorey`
    - [x] `v-g-opendoublestorey`
  - [x] letter `m`
    - [x] `v-m-longleg`
    - [x] `v-m-shortleg`
  - [x] letter `t`
    - [x] `v-t-standard`
    - [x] `v-t-cross`
  - [x] letter `Q`
    - [x] `v-q-taily`
    - [x] `v-q-straight`
  - [x] letter `y`
    - [x] `v-y-straight`
    - [x] `v-y-curly`
  - [x] number `0`
    - [x] `v-zero-slashed`
    - [x] `v-zero-dotted`
    - [x] `v-zero-unslashed`
  - [x] number `1`
    - [x] `v-one-serifed`
    - [x] `v-one-hooky`
  - [x] number `3`
    - [x] `v-three-flattop`
    - [x] `v-three-twoarks`
  - [x] tilde `~`
    - [x] `v-tilde-high`
    - [x] `v-tilde-low`
  - [x] asterisk `*`
    - [x] `v-asterisk-high`
    - [x] `v-asterisk-low`
    - [x] `v-asterisk-hexhigh`
    - [x] `v-asterisk-hexlow`
  - [x] paragraph `¶`
    - [x] `v-paragraph-high`
    - [x] `v-paragraph-low`
  - [x] underscore `_`
    - [x] `v-underscore-high`
    - [x] `v-underscore-low`
  - [x] caret `^`
    - [x] `v-caret-high`
    - [x] `v-caret-low`
  - [x] percent `%`
    - [x] `v-percent-dots`
    - [x] `v-percent-rings`
  - [x] at `@`
    - [x] `v-at-long`
    - [x] `v-at-fourfold`
    - [x] `v-at-short`
  - [x] eszet `ß`
     - [x] `v-eszet-traditional`
     - [x] `v-eszet-sulzbacher`
  - [x] curly braces `{}`
     - [x] `v-brace-straight`
     - [x] `v-brace-curly`
  - [x] dollar `$`
     - [x] `v-dollar-open`
     - [x] `v-dollar-through`
     - [x] `v-dollar-opencap`
     - [x] `v-dollar-throughcap`
  - [x] numbersign `#`
     - [x] `v-numbersign-upright`
     - [x] `v-numbersign-slanted`

**Comment by robertgzr** [comment]
You can even use the formula for more complicated modifications by simply editing the formula with `brew edit iosevka` before running the install.

Look for the block that writes the planfile:
```ruby
File.open("private-build-plans.toml", "w:UTF-8") { |f|
...
end
```

and insert your own options at the appropriate location like:
```diff
  f.puts "design = [\"#{design.join('", "')}\"]"
+ f.puts "italic = [\"v-eszet-traditional\"]"
  f.puts "\n"
```

**Comment by robertgzr** [comment]
for anybody stumbling over this when looking for a formula to build iosevka from source:

I don't really use a mac much anymore :P I'm not sure when I will around to updating this to version 3.x. Most likely I will do at some point when I have some time/need for it.

Until then if anybody wants to submit a pr, you're very welcome to do so :)

**Comment by bob-swinkels** [comment]
Thank you for your excellent work on the Isoveka formula. 

I discovered it yesterday wanted to use it; then, I found that it didn't yet support version 3.7, so I updated the formula to support the newest version at this moment. I've changed a few things to match the new documentation better and removed no longer used styles.

> Until then if anybody wants to submit a pr, you're very welcome to do so :)

I've done precisely that #13.

Please let me know if there is something that should be changed :)
